# Generated by Django 3.0.2 on 2020-01-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnlearn', '0002_lector_date_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnlearn.Lector')),
            ],
        ),
    ]
