# Generated by Django 3.0.2 on 2020-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnlearn', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'C++')], default=1),
        ),
    ]
